coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "nagraj/templates/**/*" # Ignore template files
  - "tests/**/*" # Ignore test files

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
