name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch at least 2 commits for codecov to work properly

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests with coverage
        run: |
          poetry run pytest tests/ --cov=nagraj --cov-report=xml --cov-config=.coveragerc

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false # Don't fail CI if codecov upload fails
          verbose: true # Add verbose output for debugging
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run linters
        run: |
          poetry run ruff check .
          poetry run mypy --config-file mypy.ini --verbose --show-error-codes nagraj/
